export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERMINAL=alacritty
export EDITOR=vim
export VISUAL=vim
export BROWSER=brave
export FZF_DEFAULT_OPS="--extended"
export MANPAGER='/bin/zsh -c "vim -Rn -c \"set buftype=nofile showtabline=0 ft=man ts=4 nomod nolist nornu nonu noma\" -c \"normal L\" -c \"nmap q :qa<CR>\"</dev/tty <(col -b)"'

export PATH="/home/josh/.local/bin:$PATH"

export TERM=xterm-256color

export OPENSSL_DIR=/usr/bin/openssl
export QT_QPA_PLATFORMTHEME=qt5ct

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export WALLPAPERS_DIR=$HOME/Pictures/Wallpapers
export SCREENSHOTS_DIR=$HOME/Pictures/Screenshots
export SCRIPTS_DIR=$HOME/.local/bin

export LESSHISTFILE=$XDG_CACHE_HOME/less_history
export LESSHISTSIZE=500

export LF_ICONS="\
    tw=ﱮ:\
    st=ﱮ:\
    ow=ﱮ:\
    di=ﱮ:\
    dt=ﱮ:\
    fi=:\
    ln=:\
    or=:\
    ex=:\
    *.vimrc=:\
    *.viminfo=:\
    *.gitignore=:\
    *.c=:\
    *.cc=:\
    *.clj=:\
    *.coffee=:\
    *.cpp=:\
    *.css=:\
    *.d=:\
    *.dart=:\
    *.erl=:\
    *.exs=:\
    *.fs=:\
    *.go=:\
    *.h=:\
    *.hh=:\
    *.hpp=:\
    *.hs=:\
    *.html=:\
    *.java=:\
    *.jl=:\
    *.js=:\
    *.json=:\
    *.lua=:\
    *.md=:\
    *.php=:\
    *.pl=:\
    *.pro=:\
    *.py=:\
    *.rb=:\
    *.rs=:\
    *.scala=:\
    *.ts=:\
    *.vim=:\
    *.cmd=:\
    *.ps1=:\
    *.sh=:\
    *.bash=:\
    *.zsh=:\
    *.fish=:\
    *.tar=:\
    *.tgz=:\
    *.arc=:\
    *.arj=:\
    *.taz=:\
    *.lha=:\
    *.lz4=:\
    *.lzh=:\
    *.lzma=:\
    *.tlz=:\
    *.txz=:\
    *.tzo=:\
    *.t7z=:\
    *.zip=:\
    *.z=:\
    *.dz=:\
    *.gz=:\
    *.lrz=:\
    *.lz=:\
    *.lzo=:\
    *.xz=:\
    *.zst=:\
    *.tzst=:\
    *.bz2=:\
    *.bz=:\
    *.tbz=:\
    *.tbz2=:\
    *.tz=:\
    *.deb=:\
    *.rpm=:\
    *.jar=:\
    *.war=:\
    *.ear=:\
    *.sar=:\
    *.rar=:\
    *.alz=:\
    *.ace=:\
    *.zoo=:\
    *.cpio=:\
    *.7z=:\
    *.rz=:\
    *.cab=:\
    *.wim=:\
    *.swm=:\
    *.dwm=:\
    *.esd=:\
    *.jpg=:\
    *.jpeg=:\
    *.mjpg=:\
    *.mjpeg=:\
    *.gif=:\
    *.bmp=:\
    *.pbm=:\
    *.pgm=:\
    *.ppm=:\
    *.tga=:\
    *.xbm=:\
    *.xpm=:\
    *.tif=:\
    *.tiff=:\
    *.png=:\
    *.svg=:\
    *.svgz=:\
    *.mng=:\
    *.pcx=:\
    *.mov=:\
    *.mpg=:\
    *.mpeg=:\
    *.m2v=:\
    *.mkv=:\
    *.webm=:\
    *.ogm=:\
    *.mp4=:\
    *.m4v=:\
    *.mp4v=:\
    *.vob=:\
    *.qt=:\
    *.nuv=:\
    *.wmv=:\
    *.asf=:\
    *.rm=:\
    *.rmvb=:\
    *.flc=:\
    *.avi=:\
    *.fli=:\
    *.flv=:\
    *.gl=:\
    *.dl=:\
    *.xcf=:\
    *.xwd=:\
    *.yuv=:\
    *.cgm=:\
    *.emf=:\
    *.ogv=:\
    *.ogx=:\
    *.aac=:\
    *.au=:\
    *.flac=:\
    *.m4a=:\
    *.mid=:\
    *.midi=:\
    *.mka=:\
    *.mp3=:\
    *.mpc=:\
    *.ogg=:\
    *.ra=:\
    *.wav=:\
    *.oga=:\
    *.opus=:\
    *.spx=:\
    *.xspf=:\
    *.pdf=:\
    *.nix=:\
    "
