music_directory		"$HOME/Music"
playlist_directory	"$HOME/.config/mpd/playlists"
db_file			    "$HOME/.config/mpd/mpd.db"
log_file			"syslog"
pid_file			"/tmp/mpd.pid"
state_file			"$HOME/.config/mpd/state"
sticker_file		"$HOME/.config/mpd/sticker.sql"

#bind_to_address     "127.0.0.1"
bind_to_address     "0.0.0.0"
port                "6600"

restore_paused      "yes"
auto_update         "yes"
filesystem_charset  "UTF-8"

input {
    plugin "curl"
}

audio_output {
	type		"fifo"
	name		"Visualizer Feed"
	path		"/tmp/mpd.fifo"
	format		"44100:16:2"
    mixer_type  "software"
}

audio_output {
	type		"pulse"
	name		"My Pulse Device"
}
