format = """
$status\
${custom.icon}\
[](bg:#282C34 fg:#81A1C1)\
[](bg:#6E7C99 fg:#282C34)\
$directory\
[](bg:#282C34 fg:#6E7C99)\
[](bg:#06969A fg:#282C34)\
${custom.docker}\
[](bg:#282C34 fg:#06969A)\
[](bg:#33658A fg:#282C34)\
$cmd_duration\
[](bg:#282C34 fg:#33658A)\
[](bg:#86BBD8 fg:#282C34)\
$git_branch\
$git_status\
[ ](fg:#86BBD8)\
"""

command_timeout = 5000

[status]
style = "fg:#FFFFFF bg:#81A1C1"
symbol = ""
format = '[ $symbol ]($style)'
disabled = false

[custom.icon]
description = "Display icon for each home folder"
command = """
if [ "$PWD" = "$HOME" ]; then
    echo ""
elif [ "$PWD" = "$HOME/Documents" ]; then
    echo ""
elif [ "$PWD" = "$HOME/Downloads" ]; then
    echo "ﲐ"
elif [ "$PWD" = "$HOME/Music" ]; then
    echo ""
elif [ "$PWD" = "$HOME/Pictures" ]; then
    echo ""
elif [ "$PWD" = "$HOME/Videos" ]; then
    echo ""
else
    echo "ﱮ"
fi
"""
when = "true"
style = "fg:#FFFFFF bg:#81A1C1"
format = '[ $output ]($style)'

[directory]
style = "fg:#FFFFFF bg:#6E7C99"
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = "..."

[cmd_duration]
min_time = 500
style = "fg:#ffffff bg:#33658A"
format = "[ 󰔛 $duration  ]($style)"
disabled = false

[git_branch]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ ($all_status) ]($style)'

[custom.docker]
description = "Shows the docker symbol if the current directory has Dockerfile or docker-compose.yml files"
style = "bg:#06969A"
format = '[$symbol]($style)'
symbol = "  "
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
when = """ command -v docker &> /dev/null; exit (echo $?); """
disabled = false
