format = """
$status\
${custom.icon}\
[](fg:#5FAFFF bg:#282C34)\
[](fg:#282C34 bg:#3E4452)\
$directory\
[](fg:#3E4452 bg:#282C34)\
[](fg:#282C34 bg:#5FAFFF)\
$time\
[](fg:#5FAFFF bg:#282C34)\
[](fg:#282C34 bg:#3E4452)\
$cmd_duration\
[](fg:#3E4452 bg:#282C34)\
[](fg:#282C34 bg:#5FAFFF)\
$git_branch\
$git_status\
[ ](fg:#5FAFFF)\
"""

command_timeout = 5000
add_newline = true

[status]
style = "fg:#FF0000 bg:#5FAFFF"
symbol = ""
format = "[ $symbol ]($style)"
disabled = false

[custom.icon]
description = "Display icon for each home folder"
command = """
if [[ "$PWD" = "$HOME" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Documents" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Downloads" ]]; then
    echo "ﲐ "
elif [[ "$PWD" = "$HOME/Music" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Pictures" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Videos" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/.local/bin" ]]; then
    echo " "
else
    echo "ﱮ "
fi
"""
when = "true"
style = "fg:#3E4452 bg:#5FAFFF"
format = "[ $output ]($style)"

[directory]
style = "fg:#FFFFFF bg:#3E4452"
format = "[ $path ]($style)"
truncate_to_repo = true
truncation_length = 2
truncation_symbol = "..."
home_symbol = "~"
fish_style_pwd_dir_length = 2
use_logical_path = true
use_os_path_sep = true

[time]
style = "fg:#FFFFFF bg:#5FAFFF"
format = "[  $time ]($style)"
time_format = "%l:%M%P"
disabled = true

[cmd_duration]
min_time = 750
style = "fg:#FFFFFF bg:#3E4452"
format = "[ 神$duration ]($style)"
disabled = false

[git_branch]
style = "fg:#FFFFFF bg:#5FAFFF"
format = "[ $symbol $branch]($style)"
symbol = " "

[git_status]
style = "fg:#FFFFFF bg:#5FAFFF"
format = "[ ($all_status) ]($style)"
